dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: channelape-github
    token:
      secure: VX0HYae7Qv30ujQdH0qzR5ZKqJCqdnYT69V9Rnrl2NUKS40ZwgCROk20F+QKsXp2+SwU5KPYFhTVqQbMIQ0ObaHP4xy68XjYdQYLqro5SBhktyQI2IXUMHjqww6YFcPpxNXIrfy/L4VUq83iQNoecBhzvlr+k9njhcbuBK1mrCggNdadE0CEBoJGggUtwsuSzzrwy8pHZ15NlHhhlo5PefaGtEbiLrBLL+A1+Xc6kq63uJiDx26xVDWRRqs8paDvXRwMLVBFIqEEA0ImjvgQWTEx2HNGf6t9Cg2Ya5z1GkI/Ihkopxu7TmcXAj+opMdT4d3haxZVTeCIF7CaaUG10Fnx5Pd20Gb5pEIZhgkq6irIkTrmFKk0yIfQOxUp+/P10L0IyTEi+qbiHeaLDPrdyxUtPQIgizI3hEvjpTz8QMREa7bJ8ySLSVYAyQv57NWHLoxoBnG+gQ08HCvmcz1uChMwB0lbiwe4WY2KlmOSQTA5fHBeW00hMUD9nGaeL7UYHqkM6lOmwgaTjTPFeCxaCaZZP2n8StY87+Yn3eKLA5k4hV8rSyISMQLYl6fKcLlzVI2ZgRgX6x2e2LkZlC/WDwhBHOo/n36iwMFclySaJEqtRgsY8LxWe+5/rI3jPJhz8pUsQtOIqRuAD6Hvo6HfQZ0H8xbYW6TNkSK6xshwnPE=
language: node_js
node_js:
- 8
jdk:
- oraclejdk8
install:
- npm install
script:
- npm test
after_success:
- bash .travis/overwrite-sonar-project-version.sh
- sonar-scanner
cache:
  directories:
  - node_modules
  - "$HOME/.sonar/cache"
deploy:
  provider: npm
  email:
    secure: qrj+6AbG8c9bnMv+aCHFAPe6npLx0XDNrArKPbJsC7cC0kdTrBE06kxrdsVtFyoL8aqzsmk7BzCcmi8QdqW3mjXqq9DYoH14bpkTEmwnLndOF85cPPtlaud1NAvCQsKtCWd3a86SlKxG3bn9WcUP3SznmXiDlvOahu3QQiCath+t2/dB5di5NcRyvc7SmyGJ73nRqxgMrKUOaivDpOa17sC6lyqOMO2S8CyMS0BK3FKHWFIVcGMi/8XpGoKTpoVeMu2ESHEOV4QKxkS0umJKp0UyinGN9CIorwwh8DRV9mgKgq7v2gDYkwHiMjtGv0Z7+NsLDfNnFy9dgWRKUtQ+/haxjz+W1XZ7f6IoMFpRiL0vv2TWwXXoOed3qY6OJeyRsTufmNyQLNp/aR5U3z0XbKJozNhXyXXW7m9Uvs8X/AjbH1JFQNofpgFETXSASe0izNetKvg6OBPyGBRjfvYckW1NAj0zbnjr5Q6Zc+IZaND53P7ZwpNVBH5MKKsS4YQ728wAnyAMNmJrK1F1lXQYzulLtl9gM+wFscUBYPlPcWmiriRuKizxsFgv7Mm526y4Kf+T4/YOenW/ai3xrp+AWB6mO2EU36PeQbEXpFLuYRY2psQMQswMfyqqMbU3MA0FY+wKpi97+minOvim7I0rvf+f/5gC/7/FQ0VpHXqX8CA=
  api_key:
    secure: EUOBrbDjI2ObMVin0MTam1grKzbVZgNme6e16C19cX6DNLVLr6I3Lizii3HlArbVd8TUwjZLnmS7gaNX5jN38v4h96+i0dxEN6qAIXmShBO0plnSSEC1cVBSPtilpf5NHilYt60c61bweL6YNTYEQxn3IkpMU87o9sd8P6K1rdLwOCs96P/XpgRsDdBQChTtSWXVnlGcW3Ltalv9xIYhpNNvfqeQtLaKfriNbPp4l8oupRsS461S2f1ROP6FciLpwWbro6sD0qyWJbmM27wSdLb/ekcUNvFdfz81zWRG0IQ81BEaImq9hRFZYo19rdf1HCSQDiYQ60L8RpoQrO3HI93DboutDaUfCrY3M58ak26Dk/Zm1m+/zNPBOdGQrfr8ROTQvTZ/diazFW/pdZF0k6oZmGF5qZ7MWN+6bCEE+ObesXh7sRf17JrhI4jIT81tAzXhFdCCioh+1RdC67KHr/8LGSo6UZIBLIqlM5NCjfpqHiyDYDusbv3GQGm2cDcowOoWI0OKIg+flB+H1wXVQakyNuQ/I6y8QB+ezn84zgei9x00thiBBU2qoqamz/jKFcN1a20PWS5ct9WJYyNGVdq5n+C+yQuhaeng9hOF7eG6a4OPYgIGyyOShvEXKu+mNEBd952TH4SBu/xBcEf1caNQH5HnGpyX2RaFwgHPCvA=
  on:
    tags: true
    repo: ChannelApe/generator-channelape
